# =================================================================
# 🚀 GitHub Actions Toolkit 使用示例
# =================================================================
# 本示例展示了如何在项目中使用 chengzao/toolkit-actions
# 包含本地使用和外部仓库引用的完整配置
# =================================================================

name: CI/CD Pipeline with Toolkit Actions

on:
  push:
    branches: [main, master]
    paths:
      - 'package.json'
      - 'src/**'
      - 'lib/**'
      - 'dist/**'

  pull_request:
    branches: [main, master]

# 启用 GitHub Packages 发布权限
permissions:
  contents: read
  packages: write

jobs:
  # ============================================
  # 📦 发布包到 GitHub Packages
  # ============================================
  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: 📥 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔧 发布包到 GitHub Packages
        uses: chengzao/toolkit-actions/publish-package@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          node-version: '20'
          package-manager: 'yarn'
          build-script: 'build'
          registry: 'npm.pkg.github.com'
          scope: '@your-organization'  # ⚠️ 请替换为你的组织作用域

  # ============================================
  # 🏷️ 版本变更时自动创建标签
  # ============================================
  version-tag:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' &&
      contains(github.event.head_commit.modified, 'package.json')

    steps:
      - name: 📥 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🏷️ 版本变更时创建标签
        uses: chengzao/toolkit-actions/tag-on-version-change@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          create_changelog: true

  # ============================================
  # 📅 每日构建并创建标签
  # ============================================
  build-and-tag:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: 📥 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📅 构建并创建标签
        uses: chengzao/toolkit-actions/build-tag@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'main'
          node-version: '20'
          create_changelog: true

  # ============================================
  # 🔍 测试和验证
  # ============================================
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 检出代码
        uses: actions/checkout@v4

      - name: 🔧 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: 📦 安装依赖
        run: yarn install

      - name: 🧪 运行测试
        run: yarn test

      - name: 🔨 构建项目
        run: yarn build