name: 'Auto Tag'
description: 'Automatically creates Git tags on version changes'
author: 'chengzao'

inputs:
  token:
    description: 'GitHub token for creating tags'
    required: true
  git_user_name:
    description: 'Git user name for commits and tags'
    required: false
    default: 'github-actions'
  git_user_email:
    description: 'Git user email for commits and tags'
    required: false
    default: 'github-actions@github.com'

outputs:
  version:
    description: 'The package version from package.json'
    value: ${{ steps.version_check.outputs.version }}
  tag_exists:
    description: 'Whether the tag already exists'
    value: ${{ steps.version_check.outputs.exists }}
  tag_created:
    description: 'Whether the tag was created successfully'
    value: ${{ steps.create_tag.outputs.tag_created }}
  tag_name:
    description: 'The name of the created tag'
    value: ${{ steps.create_tag.outputs.tag_name }}

runs:
  using: 'composite'
  steps:
    - name: Validate Node.js environment
      run: |
        echo ""
        if ! command -v node &> /dev/null; then
          echo "❌ Node.js is not installed or not in PATH"
          exit 1
        fi

        if ! command -v npm &> /dev/null; then
          echo "❌ npm is not installed or not in PATH"
          exit 1
        fi

        echo "✅ Node.js environment validation passed"
        echo "📦 Node.js version: $(node --version)"
        echo "📦 npm version: $(npm --version)"
      shell: bash

    - name: Check if version changed
      id: version_check
      run: |
        echo ""
        VERSION=$(node -p "require('./package.json').version")
        echo "Current version: $VERSION"

        if git tag --list "v$VERSION" | grep -q "^v$VERSION$"; then
          echo "⚠️ Tag v$VERSION already exists"
          echo "exists=true" >> "$GITHUB_OUTPUT"
        else
          echo "⚠️ Tag v$VERSION does not exist"
          echo "exists=false" >> "$GITHUB_OUTPUT"
        fi
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Create Git tag
      id: create_tag
      if: steps.version_check.outputs.exists == 'false'
      run: |
        echo ""
        git config --global user.name "$GIT_USER_NAME"
        git config --global user.email "$GIT_USER_EMAIL"

        VERSION="$STEP_VERSION"
        TAG_NAME="v$VERSION"

        echo "🏷️ Creating tag: $TAG_NAME"
        git tag -a "$TAG_NAME" -m "Release $TAG_NAME"

        # set tag name output parameters
        echo "tag_name=$TAG_NAME" >> "$GITHUB_OUTPUT"

        echo "📤 Pushing tag to origin..."
        if git push origin "$TAG_NAME"; then
          echo "✅ Successfully created and pushed tag $TAG_NAME"
          echo "tag_created=true" >> "$GITHUB_OUTPUT"
        else
          echo "❌ Failed to push tag $TAG_NAME"
          echo "tag_created=false" >> "$GITHUB_OUTPUT"
          echo "tag_name=" >> "$GITHUB_OUTPUT"  # clear tag name because creation failed
          exit 1
        fi
      shell: bash
      env:
        GIT_USER_NAME: ${{ inputs.git_user_name }}
        GIT_USER_EMAIL: ${{ inputs.git_user_email }}
        STEP_VERSION: ${{ steps.version_check.outputs.version }}