name: 'Auto Tag and Changelog'
description: 'Automatically creates Git tags on version changes and generates changelog with changelogithub'
author: 'chengzao'

inputs:
  token:
    description: 'GitHub token for creating tags and changelog'
    required: true
  create_changelog:
    description: 'Whether to create changelog using changelogithub'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Validate Node.js environment
      run: |
        if ! command -v node &> /dev/null; then
          echo "❌ Node.js is not installed or not in PATH"
          exit 1
        fi

        if ! command -v npm &> /dev/null; then
          echo "❌ npm is not installed or not in PATH"
          exit 1
        fi

        echo "✅ Node.js environment validation passed"
        echo "📦 Node.js version: $(node --version)"
        echo "📦 npm version: $(npm --version)"
      shell: bash

    - name: Check if version changed
      id: version_check
      run: |
        VERSION=$(node -p "require('./package.json').version")
        echo "Current version: $VERSION"

        if git tag --list "v$VERSION" | grep -q "^v$VERSION$"; then
          echo "⚠️ Tag v$VERSION already exists"
          echo "exists=true" >> "$GITHUB_OUTPUT"
        else
          echo "⚠️ Tag v$VERSION does not exist"
          echo "exists=false" >> "$GITHUB_OUTPUT"
        fi
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Create Git tag
      if: steps.version_check.outputs.exists == 'false'
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

        VERSION="$STEP_VERSION"
        TAG_NAME="v$VERSION"

        echo "🏷️ Creating tag: $TAG_NAME"
        git tag -a "$TAG_NAME" -m "Release $TAG_NAME"

        echo "📤 Pushing tag to origin..."
        if git push origin "$TAG_NAME"; then
          echo "✅ Successfully created and pushed tag $TAG_NAME"
        else
          echo "❌ Failed to push tag $TAG_NAME"
          exit 1
        fi
      shell: bash
      env:
        STEP_VERSION: ${{ steps.version_check.outputs.version }}

    - name: Create Changelog
      if: steps.version_check.outputs.exists == 'false' && inputs.create_changelog == 'true'
      run: |
        echo "📝 Creating changelog..."
        if npx changelogithub; then
          echo "✅ Changelog created successfully"
        else
          echo "⚠️ Failed to create changelog, but continuing..."
        fi
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}