name: 'Build and Tag'
description: 'Creates versioned tags with date prefix for releases'
author: 'chengzao'

inputs:
  token:
    description: 'GitHub token for creating tags and changelog'
    required: true
  prefix:
    description: 'Prefix name to use in tag name'
    required: false
    default: 'release'
  git_user_name:
    description: 'Git user name for commits and tags'
    required: false
    default: 'github-actions'
  git_user_email:
    description: 'Git user email for commits and tags'
    required: false
    default: 'github-actions@github.com'

outputs:
  tag_name:
    description: 'The name of the created tag'
    value: ${{ steps.create_tag.outputs.tag_name }}
  tag_created:
    description: 'Whether the tag was created successfully'
    value: ${{ steps.create_tag.outputs.tag_created }}
runs:
  using: 'composite'
  steps:
    - name: Validate Node.js environment
      run: |
        echo ""
        echo "============== 🏷️ Validate Node.js environment =============="
        if ! command -v node &> /dev/null; then
          echo "❌ Node.js is not installed or not in PATH"
          exit 1
        fi

        if ! command -v npm &> /dev/null; then
          echo "❌ npm is not installed or not in PATH"
          exit 1
        fi

        echo "✅ Node.js environment validation passed"
        echo "📦 Node.js version: $(node --version)"
        echo "📦 npm version: $(npm --version)"
      shell: bash

    - name: Verify trigger Info
      run: |
        echo ""
        echo "=================== 🏷️ Verify trigger Info ==================="
        echo "📁 Event Name: ${{ github.event_name }}"
        echo "🏠 Repository: ${{ github.repository }}"
        echo "👤 Actor: ${{ github.actor }}"
        echo "🔍 Sender: ${{ github.event.sender.login }}"
        echo "🌿 Branch: ${{ github.ref_name }}"
        echo "👤 Commit Author: ${{ github.event.head_commit.author.name || 'N/A' }}"
        echo "📅 Commit Time: ${{ github.event.head_commit.timestamp || 'N/A' }}"
        echo "🔗 Commit URL: ${{ github.event.head_commit.url || 'N/A' }}"
      shell: bash

    - name: Create a release tag
      id: create_tag
      run: |
        echo ""
        echo "=================== 🏷️ Creating release tag ==================="
        git config --global user.name "$GIT_USER_NAME"
        git config --global user.email "$GIT_USER_EMAIL"

        # Current Time
        DATE=$(date +"%Y_%m_%d")

        # Branch name
        CURRENT_BRANCH="$INPUT_PREFIX"

        # Get latest tag
        LATEST_TAG=$(git tag -l "${CURRENT_BRANCH}_${DATE}_v*" | sort -V | tail -n1)
        # if current day has no tag, start from v1.
        if [ -z "$LATEST_TAG" ]; then
            VERSION=1
        else
            # get current latest version
            VERSION=${LATEST_TAG#*v}
            # increment the version
            ((VERSION++))
        fi

        # create new tag name
        TAG_NAME="${CURRENT_BRANCH}_${DATE}_v${VERSION}"

        echo "🏷️ Creating tag: $TAG_NAME"
        git tag -a "$TAG_NAME" -m "Release $TAG_NAME"

        echo "📤 Pushing tag to origin..."
        # set default value
        echo "tag_name=$TAG_NAME" >> "$GITHUB_OUTPUT"
        
        if git push origin $TAG_NAME; then
          echo "✅ Tag $TAG_NAME pushed successfully"
          echo "tag_created=true" >> "$GITHUB_OUTPUT"
        else
          echo "❌ Failed to push tag $TAG_NAME"
          echo "tag_created=false" >> "$GITHUB_OUTPUT"
          echo "tag_name=" >> "$GITHUB_OUTPUT"  # clear tag name because creation failed
          exit 1
        fi
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        INPUT_PREFIX: ${{ inputs.prefix }}
        GIT_USER_NAME: ${{ inputs.git_user_name }}
        GIT_USER_EMAIL: ${{ inputs.git_user_email }}
